services:
  - type: web
    name: online-store
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn online_store.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: online_store.settings
      - key: PYTHON_VERSION
        value: 3.10
    staticPublishPath: staticfiles
